name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub registry
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build, tag and push Docker image to Docker Hub registry
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/containerized_webapp_deploy:latest
